services:
  - type: web
    name: craftgardening-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      # Set MONGODB_URI and JWT_SECRET in Render dashboard


